FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

COPY client ./client
COPY packages ./packages 

RUN pnpm install

WORKDIR /app/client

EXPOSE 3000

CMD ["pnpm", "dev"]